### PR TITLE
transform-biosample: update submitting_lab for EBI

### PR DESCRIPTION
**Pull request by joverlee521**
BioSample records pulled from EBI/ENA have owners as "EBI" or
"European Bioinformatics Institute" but we want to acknowledge the
original submitting lab that had submitted the sequences to EBI/ENA.

For records with "EBI" as the owner, the original submitter is stored
in the `INSDC center name` attribute.

For records with "European Bioinformatics Institute" as the owner, the
original submitter is stored in the `sampleIds` field within `db`
of the sample id that is labeled as "Sample name".

### CODE REVIEW

**Review by MoiraZuber — APPROVED** [review]
Looks good! Since the special case for "European Bioinformatics Institute" was not discussed in the Slack thread, could you maybe post one or two example sequences that are affected by this change? Just to have an impression of what to expect from these fields!

**Comment by emmahodcroft** [comment]
Thank you so much Jover! I agree with Moira though - I'm a little unclear on what the processing for "European Bioinformatics Institute" is - could you clarify a little bit? 

Apart from that, I think this looks great and is good-to-go!

**Comment by joverlee521** [comment]
Thanks for taking a look @MoiraZuber @emmahodcroft!

For the "European Bioinformatics Institute" records, the info doesn't show up on the website (see: [SAMEA6847752](https://www.ncbi.nlm.nih.gov/biosample/SAMEA6847752) or [SAMEA6915227](https://www.ncbi.nlm.nih.gov/biosample/SAMEA6915227)), but the records in the `biosample.ndjson` contain the following (I only included the fields that are relevant):
```json
{
 "accession":"SAMEA6847752",
 "owner":{"contacts":[{"lab":"European Nucleotide Archive"}],"name":"European Bioinformatics Institute"},
 "sampleIds":[{"db":"ERASMUS MC, UNIVERISTY MEDICAL CENTER","label":"Sample name","value":"Run169_BC10"},{"db":"SRA","value":"ERS4575350"}]
}
{
 "accession":"SAMEA6915227",
 "owner":{"contacts":[{"lab":"European Nucleotide Archive"}],"name":"European Bioinformatics Institute"},
 "sampleIds":[{"db":"Wellcome Sanger Institute","label":"Sample name","value":"COG-UK/CAMB-77329"},{"db":"SRA","value":"ERS4625155"}]
}

```
The submitting labs that I am able to pull out for these records are the following:
```
COVID-HUB-PL
ERASMUS MC, UNIVERISTY MEDICAL CENTER
ETH ZURICH D-BSSE
Friedrich-Loeffler-Institute
Heinrich-Pette-Institute, Leibniz-Institute for experimental Virology
Quadram Insititute Bioscience
Quadram Institute Bioscience
SCILIFELAB STOCKHOLM
University of Birmingham
Wellcome Sanger Institute
```

**Comment by emmahodcroft** [comment]
Thank you for the clarification @joverlee521 and the examples! 

Ok, that's interesting. I notice both of these examples are from 2020, so perhaps this is a bit of a hang-over from early sharing of data between the systems, and that might be why it's different?

But from what you've shown and your examples, this seems to be a sensible way to process those, and the results you're getting out seem sensible & 'taggable'! 
Does all seem good to you @MoiraZuber ?



>Quadram Insititute Bioscience
Quadram Institute Bioscience

Glad I'm not the only one who tends to get lost somewhere in the middle of trying to spell Institute 😅

**Comment by MoiraZuber** [comment]
This is looking good to me!

**Review by emmahodcroft — APPROVED** [review]

**Comment by emmahodcroft** [comment]
Fantastic! I'm not 100% sure why the first check failed - as it shows a second (seemingly the same?) succeeded. Anyway - if all seems ok, @joverlee521 , feel free to merge!

**Comment by joverlee521** [comment]
> I'm not 100% sure why the first check failed - as it shows a second (seemingly the same?) succeeded. Anyway - if all seems ok, @joverlee521 , feel free to merge!

I manually cancelled the first check since this change doesn't affect the GISAID ingest. I figured we don't need to be wasting resources 😄

**Pull request merged**
