### PR TITLE
Updates to genbank_accession lines (529 new, seqs downloaded 2020-12-18)

### PR DESCRIPTION
**Pull request by AngieHinrichs**
Another bi-weekly update of genbank accessions matched by 1. sequences being identical (possibly except for runs of N's at beginning and/or end) and 2. similar country/isolate/year names.

Last update in 2020!  Just 529 new genbank_accessions this time.

Thanks & happy holidays!

### CODE REVIEW

**Comment by AngieHinrichs** [comment]
529 seemed awfully small and it was -- I missed some new sequences.  Closing this for now, should be able to fix it soon.

**Comment by AngieHinrichs** [comment]
I didn't have quite all of the latest sequences the first time around -- now there are 1418 new mappings which is more in line with what I would expect after two weeks.  Thanks again!

**Comment by emmahodcroft** [comment]
Thank you Angie!! As always your work on this is always so appreciated!

**Comment by AngieHinrichs** [comment]
Thank you Emma!  :)

**Pull request merged**
