### PR TITLE
chore: bump action versions for node update from 12->16

### PR DESCRIPTION
**Pull request by corneliusroemer**
- chore: bump gh actions/checkout@v2 to v3
- chore: bump docker actions from v1 to v2
- chore: bump docker/build-push-action from v2 to v3

Migration necessary due to Github requiring all actions to use node 16 by summer 2023

Things should continue to work.

We may want to do this in an automated fashion on all repos. But let's start here.

### CODE REVIEW

**Comment by victorlin** [comment]
> We may want to do this in an automated fashion on all repos

This can be achieved per-repo by [configuring dependabot to check for outdated actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot).

**Comment by corneliusroemer** [comment]
>This can be achieved per-repo by [configuring dependabot to check for outdated actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot).

Great find, we could try :)

**Comment by tsibley** [comment]
This makes a ton of other unrelated changes to the files—seemingly because they were roundtripped thru a YAML serializer with low fidelity—that unnecessarily obscure the actual changes. I'd suggest avoiding that churn.

**Comment by corneliusroemer** [comment]
Thanks @tsibley for noticing, this happened with autoformat on save and I didn't notice. It's fixed now.

**Pull request merged**
