### PR TITLE
Transition to NCBI Datasets

### LINKED ISSUE #184: Use NCBI Datasets command line tool to download SARS-CoV-2 data from GenBank
Start using the [NCBI Datasets command line tool](https://www.ncbi.nlm.nih.gov/datasets/docs/quickstarts/command-line-tools/) to download SARS-CoV-2 data from GenBank. This would replace the current [fetch-from-genbank script](https://github.com/nextstrain/ncov-ingest/blob/master/bin/fetch-from-genbank), which has been consistently failing over the last few weeks. 

I think we would mostly be interested in the [virus metadata report](https://www.ncbi.nlm.nih.gov/datasets/docs/data-packages/sars-cov-2-genome/#virus-data-report) and the [genomic FASTA](https://www.ncbi.nlm.nih.gov/datasets/docs/data-packages/sars-cov-2-genome/#genomic-fasta). 

This will also require some updates to the [transform-genbank script](https://github.com/nextstrain/ncov-ingest/blob/master/bin/transform-genbank) since the metadata and sequences will be in separate files instead of one NDJSON.

### PR DESCRIPTION
**Pull request by joverlee521**
### Description of proposed changes

Transition to using NCBI Datasets to fetch GenBank records. NCBI Datasets has a cached virus data package for all SARS-CoV-2 genomes, so the download is much faster than the fetch from NCBI Virus. 

This produces an NDJSON file with the NCBI field names instead of our internal field names, which I think is fine since we do not publicly advertise the genbank.ndjson file. The `transform-genbank` pipeline has been updated to use the new field names, so we can no longer use it for the previous NDJSON files. I don't think there's any reason why we need to keep this backwards compatible, but please let me know if I've missed something. 

### Related issue(s)

Resolves #184 

### Testing

- [x] Checks pass
- [x] Test GenBank run (AWS Batch job id `84ebd7b4-1a3c-4479-abf8-785add6efa55`)

### CODE REVIEW

**Comment by joverlee521** [comment]
Comparing yesterday's scheduled run (`29940944-c6c3-4141-8e4c-37d6a9aba23d`) to the test run (`84ebd7b4-1a3c-4479-abf8-785add6efa55`): 

|                 | Scheduled Run | Test Run | Diff |
|----------|-----------------|----------| ----|
| Run time | 713 minutes | 458 minutes | -255 minutes |
| NDJSON records | 6,545,783 | 6,501,520 | -44,263 |
| Metadata records | 7,137,467 | 7,093,324 | -44,143 |

The missing ~44,000 records is worrisome, I'm asking NCBI folks if there's some filtering or delay in the NCBI Datasets virus package.

**Comment by corneliusroemer** [comment]
Thanks a lot for this @joverlee521 

1. `augur curate passthru` seems pretty slow, the rule `create_genbank_ndjson` that just seems to do some reformatting takes 3h15min. Not blocking but if we want to reduce runtime this is one place.

```txt
    538 [batch] [2022-12-19T20:52:00+01:00] rule create_genbank_ndjson:
    539 [batch] [2022-12-19T20:52:00+01:00]     input: data/ncbi_dataset_sequences.fasta, data/ncbi_dataset_report.tsv
    540 [batch] [2022-12-19T20:52:00+01:00]     output: data/genbank.ndjson
    541 [batch] [2022-12-19T20:52:00+01:00]     log: logs/create_genbank_ndjson.txt
    542 [batch] [2022-12-19T20:52:00+01:00]     jobid: 37
    543 [batch] [2022-12-19T20:52:00+01:00]     benchmark: benchmarks/create_genbank_ndjson.txt
    544 [batch] [2022-12-19T20:52:00+01:00]         augur curate passthru             --metadata data/ncbi_dataset_report.tsv             --f    544 asta data/ncbi_dataset_sequences.fasta             --seq-id-column Accession             --seq-field sequence             --unmatched    544 -reporting warn             --duplicate-reporting warn             2> logs/create_genbank_ndjson.txt > data/genbank.ndjson
    545 [batch] [2022-12-19T20:52:00+01:00]         
    546 [batch] [2022-12-20T00:08:29+01:00] Removing temporary output file data/ncbi_dataset_sequences.fasta.
    547 [batch] [2022-12-20T00:08:35+01:00] Removing temporary output file data/ncbi_dataset_report.tsv.
    548 [batch] [2022-12-20T00:08:35+01:00] [Mon Dec 19 23:08:34 2022]
    549 [batch] [2022-12-20T00:08:35+01:00] Finished job 37.
```

2. If the 44k that are missing are old this isn't such a problem. I'll find out which ones are missing.

**Comment by corneliusroemer** [comment]
These are submission dates for the sequences (from metadata.tsv) not in the new download (NCBI datasets) but the old one (virus). Submission dates are spread over the last 3 weeks. It's not just the most recent day of data. But it's also nothing before end of November. Weird.

image

Here are metadata files for each of the combinations: new but not old, and old but now new:
[differences.tsv.tgz](https://github.com/nextstrain/ncov-ingest/files/10272620/differences.tsv.tgz)

**Comment by corneliusroemer** [comment]
This is how I generate these stats:
```
zstdcat meta_old.tsv.zst | tsv-filter -H --str-in-fld database:genbank --str-in-fld date_submitted:2022-12 | tsv-summarize -H -g date_submitted --count | keep-header -- sort >old_submission_dates
```

Submission dates in old way of fetching:

```
date_submitted  count
2022-12-01      5391
2022-12-02      1717
2022-12-03      512
2022-12-05      3763
2022-12-06      2061
2022-12-07      1162
2022-12-08      5122
2022-12-09      3194
2022-12-10      137
2022-12-12      8167
2022-12-13      1697
2022-12-14      3282
2022-12-15      7363
2022-12-16      3536
2022-12-17      2341
2022-12-18      726
2022-12-19      2263
```

By new way of fetching:
```
date_submitted  count
2022-12-01      5237
2022-12-02      1532
2022-12-03      314
2022-12-05      1265
```

Ah that makes it pretty clear what's going on.

**Comment by corneliusroemer** [comment]
I've triggered another run now that NCBI datasets have fixed their bug.

`d2604e9a-9bed-4ddf-bb40-d705cba09cb7`

**Comment by joverlee521** [comment]
Getting back to this again. Triggered another test run `20f7c600-0767-48c4-b205-a6421f17dd2d`

**Comment by corneliusroemer** [comment]
Just checked and it looks good. We now get strictly more sequences through datasets than using the often failing API download.

So I'd say it's ready for merge.

We should still look out for lack of new sequences though and alert NCBI if there's a lack of new data so they can fix.

**Review by corneliusroemer — APPROVED** [review]
Compared outputs and this looks great! We get strictly more data now.

**Comment by tsibley** [comment]
Leaving a breadcrumb re: https://github.com/nextstrain/ncov-ingest/issues/383 here. Looks like we lost all values for some columns with this. We can continue discussion there.

**Pull request merged**
